#ifndef DATACORRECTION_GLOBAL_H
#define DATACORRECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATACORRECTION_LIBRARY)
#  define DATACORRECTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATACORRECTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DATACORRECTION_GLOBAL_H
